### ISSUE TITLE
Some issues I meet

### ISSUE THREAD

**Issue by ghost** [CharaD7/my-vim-config#1]
# Some issues and suggestions

## The first time I failed to build vim

(Although I didn't need to manually build Vim with a Kubuntu 21.10 installation)

And then I found the the line reported for config script start in config.log:

    configure: loading cache auto/config.cache

The cache files in `vim-files/src/auto/` may cause the build to fail in a new evironment.

So I remove config.cache and try again without errors.

- _It's recommended to add a .gitignore file to ignore some cache file._

## When installing plugins I catch some errors

After retry many times I still got this error:

    fatal: unable to access 'https://github.com/oblitum/rainbow.git/'

And the plugin `rainbow` was failed to install.

The repository of rainbow plugin seems unavailable, I also unable to access [This](https://github.com/oblitum/rainbow) in my web brower.

So I manual clone it from [Here](https://github.com/luochen1990/rainbow) which similar with `Rainbow`. _(This may not be important)_

**By the way, this is the best configuration I've ever seen.**

**Thank you for your hard work.**

**Comment by CharaD7** [comment]
### Review Reply

Hello @supdrewin, thank you for trying out my configuration. I am sorry you encountered these errors. I have fixed the aspect that
had to do with the rainbow plugin and added some additional features.

I have also optimized vimrc so load time and coding with vim is much faster than before, and with diagnostics features. 

Also, I will try add an instruction for cleaning cache before compiling the vim-files. 
Normally, it's best to run ```make clean distclean``` before compiling the vim files.

To get the latest update, kindly run ```git pull``` or just copy the ```.vimrc``` file and replace the content best suited for you.

Fuzzy finder is now used in this configuration with preview options, I am currently working on using lazygit and invoking lazygit
right within vim. Do lookout for more features coming up.

If you are okay with the current configuration, kindly push the close button. 

**Thank you once again for using my configuration.**

**Comment by CharaD7** [comment]
> # Some issues and suggestions
> ## The first time I failed to build vim
> 
> (Although I didn't need to manually build Vim with a Kubuntu 21.10 installation)
> 
> And then I found the the line reported for config script start in config.log:
> 
> ```
> configure: loading cache auto/config.cache
> ```
> 
> The cache files in `vim-files/src/auto/` may cause the build to fail in a new evironment.
> 
> So I remove config.cache and try again without errors.
> 
>     * _It's recommended to add a .gitignore file to ignore some cache file._
> 
> 
> ## When installing plugins I catch some errors
> 
> After retry many times I still got this error:
> 
> ```
> fatal: unable to access 'https://github.com/oblitum/rainbow.git/'
> ```
> 
> And the plugin `rainbow` was failed to install.
> 
> The repository of rainbow plugin seems unavailable, I also unable to access [This](https://github.com/oblitum/rainbow) in my web brower.
> 
> So I manual clone it from [Here](https://github.com/luochen1990/rainbow) which similar with `Rainbow`. _(This may not be important)_
> 
> **By the way, this is the best configuration I've ever seen.**
> 
> **Thank you for your hard work.**

### Review Reply

Hello @supdrewin, thank you for trying out my configuration. I am sorry you encountered these errors. I have fixed the aspect that
had to do with the rainbow plugin and added some additional features.

I have also optimized vimrc so load time and coding with vim is much faster than before, and with diagnostics features. 

Also, I will try add an instruction for cleaning cache before compiling the vim-files. 
Normally, it's best to run ```make clean distclean``` before compiling the vim files.

To get the latest update, kindly run ```git pull``` or just copy the ```.vimrc``` file and replace the content best suited for you.

Fuzzy finder is now used in this configuration with preview options, I am currently working on using lazygit and invoking lazygit
right within vim. Do lookout for more features coming up.

If you are okay with the current configuration, kindly push the close button. 

**Thank you once again for using my configuration.**

**Comment by ghost** [comment]
No error found after `make clean distclean` and all plugins seem to be OK. Thanks!
